version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: dispetcher_dev
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root